### ISSUE TITLE
Issue with metric filter on = symbol

### ISSUE THREAD

**Issue by sidharthk** [prometheus/graphite_exporter#110]
Hi,
I am integrating Hadoop metrics with Prometheus using graphite exporter but the problem is metrics published by Hadoop daemons have = symbol and Iam unable to filter it.

For example:
Hadoop.dfs.rpc.rpc.port.Hostname=srver1.abc.com.RpcAvgResponseTime

I want to remove hostname from the metric name and map to metric name as

Hadoop.dfs.rpc.rpc.port.RpcAvgResponseTime{hostname=srver1.abc.com}.

Please help to resolve this 

Thank for your help in advance.

Regards
Sidharth

**Comment by matthiasr** [comment]
Can you share the configuration you have tried? What happened when you
tried it?

**Comment by zefir6** [comment]
I used something like this with success:

`- match: 'hadoop\.dfs\.FSNamesystem\.Context=([a-zA-Z]+)\.(?:EnabledEcPolicies=(\S+)\.)?(?:HAState=(\S+)\.)?(?:TotalSyncTimes=([\d ]+)\.)?Hostname=([0-9a-z._]+com)\.(\S+)'
  name: "cdh_dfs_FSNamesystem_${6}"
  match_type: regex
  labels:
    context: "$1"
    hostname: "$5"`

But I have problems with the space in metric name.

**Comment by sidharthk** [comment]
Hi ,

For namenode, i moved to jmx-exporter as i dint find any solution for space
in metric name.

Warm Regards

Sidharth Kumar | Skype: itzsidharth

**Comment by matthiasr** [comment]
I think that is a good solution! I consider the graphite exporter a last resort, using JMX will give you a much better experience overall.

In general, I am open to accepting any metric that Graphite accepts, if there is a need, but since you found a different way I am going to close this issue for now.
