### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by marens101** [prometheus/graphite_exporter#117]
Hi!

I'm having issues setting up.
I first tried the binaries found here:
https://prometheus.io/download/#graphite_exporter

Seemed to be working fine, until I tried to send some test data to it.

Startup:
```bash
root@MONIT-01:/opt/prometheus/graphite_exporter_0# ./graphite_exporter 
level=info ts=2020-02-16T10:02:30.856Z caller=main.go:260 msg="Starting graphite_exporter" version_info="(version=0.7.0-rc1, branch=HEAD, revision=b11c8a66bb01034aacadff5bcc6bf073b7803340)"
level=info ts=2020-02-16T10:02:30.857Z caller=main.go:261 build_context="(go=go1.13.6, user=root@5b94ccd60948, date=20200121-10:31:27)"
level=info ts=2020-02-16T10:02:30.859Z caller=main.go:341 msg="Listening on :9108"
```

Then, from another SSH session:
```bash
root@MONIT-01:~# echo "test_tcp 1234 $(date +%s)" | nc localhost 9109
root@MONIT-01:~# 
```

I immediately got pinged by the first session, which had now printed the following error before quitting:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8a7df9]

goroutine 26 [running]:
github.com/prometheus/statsd_exporter/pkg/mapper.(*MetricMapper).GetMapping(0xc000136180, 0xc0000c8400, 0x8, 0x9d0091, 0x5, 0x0, 0x0, 0x0)
        /app/vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper.go:240 +0xc9
main.(*graphiteCollector).processLine(0xc000100280, 0xc0000c8400, 0x18)
        /app/main.go:137 +0x478
main.(*graphiteCollector).processLines(0xc000100280)
        /app/main.go:123 +0x5f
created by main.newGraphiteCollector
        /app/main.go:107 +0x150
```

After fiddling for awhile (mostly reinstalling graphite_exporter and go) I thought maybe the issue was with the precompiled binary.

So I attempted to compile from source, with no luck.
This is the error I got (and keep getting): http://paste.ubuntu.com/p/NZNhdkzBkD/

Any ideas?

**Comment by marens101** [comment]
Forgot to mention, I'm running Ubuntu 18.04.1.

**Comment by matthiasr** [comment]
Thank you, for the complete report!

This seems to indeed be an issue with the [mapper update](https://github.com/prometheus/graphite_exporter/pull/116) in version 0.7.0-rc1 (@xocasdashdash could you take a look?)

Could you try the stable [0.6.2](https://github.com/prometheus/graphite_exporter/releases/tag/v0.6.2) please?

**Comment by xocasdashdash** [comment]
Sure! I'll take a look later today.

**Comment by xocasdashdash** [comment]
Ok, the bad commit is this one: 77c42572db2c9c7e75efda5ccff28a2cff343cbc . Going to see if I can fix it myself but probably it's an issue that's coming from the mapper.

**Comment by xocasdashdash** [comment]
@marens101 Hi!
So the issue pops up if you don't pass any mapping configuration, try using a sample configuration (the yaml on the readme for example) and it should work as expected. Meanwhile I'm working on a fix. 

@matthiasr About the fix, we could work around the issue (got it working already) but I feel like the best option would be to force init(https://github.com/prometheus/statsd_exporter/blob/master/pkg/mapper/mapper.go#L225-L235) the cache on the mapper side or add a guard around every cache call.

I'd go for the safe default on the mapper side an adding a regression e2e test here (like the issue61 one)

What do you think?

**Comment by matthiasr** [comment]
@marens101 I cut a new [release candidate with the fix](https://github.com/prometheus/graphite_exporter/releases/tag/untagged-c6821e2d8859bdbaef5b), could you give it a spin?

@xocasdashdash thank you for fixing it! I agree that the mapper shouldn't be surprising like that. I think the way forward is [breaking out the cache into its own package](https://github.com/prometheus/statsd_exporter/pull/281#pullrequestreview-341189222). Would you be interested in picking that up?

**Comment by xocasdashdash** [comment]
Sure! I'll take a look!
