### ISSUE TITLE
Graphite Exporter on kubernetes cluster

### ISSUE THREAD

**Issue by vishnugs** [prometheus/graphite_exporter#121]
Hi,

Can you help me with setting up graphite exporter in a kubernetes cluster ?

I dont see any yaml file or helm chart for deploying the same .

Regards
Vishnu

**Comment by matthiasr** [comment]
Hmm, I can give you a rough idea (based on how we deploy the statsd exporter in ours), if you work out the details would you be willing to make a documentation PR? I don't think we need a helm chart or anything, just an example of what would work.

We deploy the exporter as a sidecar, that is, a second container in the application pod, and make the application send metrics to localhost. For reasons entirely our own, we use an init container to put the application-specific mapping into a shared emptyDir volume; generally a configmap is probably a better choice for this.

What I don't have a solution for is also relaying the information into an existing Graphite server …
