### ISSUE TITLE
[bug] mappings is not working

### ISSUE THREAD

**Issue by millerjp** [prometheus/graphite_exporter#13]
Hi,
Possibly this is user error - but no matter what I try I cant seem to get the mappings to work.
For example:

```
# HELP _jvm_uptime Graphite metric .jvm.uptime
# TYPE _jvm_uptime gauge
_jvm_uptime 526
```

No, matter what I try for mappings it just doesnt get matched. I have tried

```
*.*
name="catchall"
first="$1"
second="$2"
third="$3"
job="$1-$2-$3"
```

```
jvm.*
name="jvm"
type="$1"
```

```
jvm.uptime
name="jvm_uptime"
type="$1"
```

Any help is appreciated.

I have tried this with the latest master code and the docker images.

The config file is definitely getting picked up (as it breaks if the syntax is invalid)

**Comment by brian-brazil** [comment]
There's a . in front of that metric, so try:

`.jvm.*`

**Comment by millerjp** [comment]
@brian-brazil yeah, I tried that both as
```.jvm.*
name="jvm"
type="$1"
```
and
```
.jvm.uptime
name="jvm_uptime_ms"
type="$1"
```
It gives an error:
```time="2016-05-17T13:26:44Z" level=fatal msg="Error loading metric mapping config: Line 0: expected metric match line, got: .jvm.uptime" file=main.go line=191
time="2016-05-17T13:27:58Z" level=fatal msg="Error loading metric mapping config: Line 0: expected metric match line, got: .jvm.*" file=main.go line=191```

**Comment by brian-brazil** [comment]
We should allow that. Try `*.jvm.*`

**Comment by millerjp** [comment]
@brian-brazil no error this time, but still doesn't find match the metric. Kinda scratching my head a bit on this one. Shouldn't the *.* catchall at least work - I see its in the tests?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/graphite_exporter/blob/master/mapper.go#L71 needs to change + to * anyway.

**Comment by millerjp** [comment]
@brian-brazil not quite sure what your asking? Do you think there's a bug?

**Comment by ajhcpt** [comment]
Hi, I'm also having a problem with mapping. 

This is the graphite data displayed on the metrics page that I want to map: 
# HELP adviserResults_summary_adviser_int_gray_net_rule_ruleScore_median Graphite metric adviserResults.summary.adviser.int.gray.net.rule.ruleScore.median
# TYPE adviserResults_summary_adviser_int_gray_net_rule_ruleScore_median gauge
adviserResults_summary_adviser_int_gray_net_rule_ruleScore_median 93

I've setup the following mapping:
*.summary.adviser.*.gray.net.rule.ruleScore.*
name="my_rulescore_median"
application="$1"
environment="$2"
measurement="$3"

I'm expecting to see this in the metrics when running with this mapping:
my_rulescore_median{application="adviser",environment="int",measurement="median"}

But I still just see:
# HELP adviserResults_summary_adviser_int_gray_net_rule_ruleScore_median Graphite metric adviserResults.summary.adviser.int.gray.net.rule.ruleScore.median
# TYPE adviserResults_summary_adviser_int_gray_net_rule_ruleScore_median gauge
adviserResults_summary_adviser_int_gray_net_rule_ruleScore_median 93

If i set "-graphite.mapping-strict-match" then no stats at all come through. Is my mapping wrong or is there an bug?

**Comment by palika** [comment]
I had a similiar issue, my config was 
```
gatling_swarm.*.*.users.allUsers.*
name="gatling_users"
node="$1"
simulation="$2"
status="$3"
job="gatling_test"
```
and the metrics gatling_swarm.pal_dev.wvsocialfeedsimulation.users.allUsers.active was not mapped properly. However, when I added an empty line to the end of the configuration file, the mapping started to work properly:

```
# HELP gatling_users Graphite metric gatling_swarm.pal_dev.wvsocialfeedsimulation.users.allUsers.active
# TYPE gatling_users gauge
gatling_users{job="gatling_test",node="pal_dev",simulation="wvsocialfeedsimulation",status="active"} 93
gatling_users{job="gatling_test",node="pal_dev",simulation="wvsocialfeedsimulation",status="done"} 54
gatling_users{job="gatling_test",node="pal_dev",simulation="wvsocialfeedsimulation",status="waiting"} 3
```

**Comment by mrpity** [comment]
Hi everyone!
I am not strong in Go, so ,maybe, you can say what i am doing wrong.

Every time when I try to export metrics to prometheus I have the following errors:
`
* collected metric jvm_memory_total label:<name:"application" value:"local-1506187560099" > label:<name:"executor_id" value:"driver" > label:<name:"mem_type" value:"used" > gauge:<value:1.44158112e+08 >  has help "Graphite metric local-1506187560099.driver.jvm.total.used" but should have "Graphite metric local-1506187560099.driver.jvm.total.max"

* collected metric jvm_memory_total label:<name:"application" value:"local-1506187560099" > label:<name:"executor_id" value:"driver" > label:<name:"mem_type" value:"committed" > gauge:<value:2.93142528e+08 >  has help "Graphite metric local-1506187560099.driver.jvm.total.committed" but should have "Graphite metric local-1506187560099.driver.jvm.total.max"
`
It looks like graphite-exporter hangs on one metric('local-1506187560099.driver.jvm.total.max'). I suppose that I was mistaken somewhere.

my graphite exporter mapping file:
`
*.*.jvm.total.*
name="jvm_memory_total"
application="$1"
executor_id="$2"
mem_type="$3"
`
Thanks in advance for any tips...
