### ISSUE TITLE
Problems importing data generated by puppet-metrics collector

### ISSUE THREAD

**Issue by rod3kartik** [prometheus/graphite_exporter#136]
I am using Puppet-metrics collector to gather some information about my server. This data is being generated in Graphite format. When I send this data over to the graphite exporter. I am getting following issue for all of the metrics collected:

INFO[0961] Invalid value in line: xxxx.xxxx.puppetserver.ca.service_version 5.3.12 1594142401

where 1594142401 is the timestamp.

**Comment by glightfoot** [comment]
This exporter expects the [value to be a float](https://github.com/prometheus/graphite_exporter/blob/e101883dc45108effd67b0f010cf019ebfb137fb/main.go#L151) since that is all that is allowed in prometheus metrics. You'll likely need to add a mapping to drop these metrics.

**Comment by rod3kartik** [comment]
Thanks!
