### ISSUE TITLE
scala spark project

### ISSUE THREAD

**Issue by songyang423915** [prometheus/graphite_exporter#137]
I have a spark project, written in scala language, but using graphite_exporter cannot get the indicators defined in the mapping, how can I solve this?

**Comment by matthiasr** [comment]
Try running the exporter with `--log.level=debug` – it will show more information about what comes in and how it is parsed.

**Comment by matthiasr** [comment]
I'm going to close this – usage questions are best put to the prometheus-users mailing list where more people see them and are available to help.
