### ISSUE TITLE
Graphite Exporter in relation with Prometheus

### ISSUE THREAD

**Issue by Eweol** [prometheus/graphite_exporter#157]
Hey guyes,

our architecture looks like
`Graphite-Exporter -> Prometheus -> Grafana`

we thought that the metrics which came in Graphite and will be scraped by Prometheus, will be stored there.
But after 5 min, so the expire time, the metrics are not available anymore.
Is there an chance to store the metrics in the Prometheus Database?

Thanks

**Comment by mdehollander** [comment]
I have the same use-case. So I wonder if you have found an solution? I have the feeling the `graphite_exporter` is for live exporting, so the existing graphite needs to stay online. Seems that this can not be used for migrating graphite data to prometheus as asked earlier #122. If anyone knows how to do this, I am happy to hear it.

**Comment by matthiasr** [comment]
I see that you already found this, but for future reference: #145 will allow migrating existing data.
