### ISSUE TITLE
Allow setting metric type

### ISSUE THREAD

**Issue by The-M1k3y** [prometheus/graphite_exporter#164]
It would be great if there was an option in the mapping to set the metric type if it's not a gauge. Makes the handling of error counters much simpler.

**Comment by matthiasr** [comment]
As far as I understand, Graphite has no concept of a counter as such. Can you say more about the use case here? What generates counters with Prometheus semantics in Graphite format?

**Comment by The-M1k3y** [comment]
I have a few "counter" metrics coming from a TrueNAS system, for example "servers.hostname.zfs_arc.memory_throttle_count", "servers.hostname.rrdcached.counter.journal-rotates" and a few more. I don't have much experience with graphite, so I don't know if this is a normal usecase or not, so my issue was more of a suggestion.

Setting the metric type to counter for these metrics allows prometheus to handle resets of these values when for example the system reboots.

**Comment by matthiasr** [comment]
I see, this is a valid request but I would like to decline it anyway. This need is an artifact of the loop through the Graphite data model, which does not have this distinction of types. Supporting a metric type override would be relatively invasive, both in terms of code and in that it adds complexity and potential confusion for users.

Right now, and at least until the next major release, Prometheus doesn't _actually_ care about the metric type, so you can use `rate()` and `increase()` on the metrics anyway to correct for resets.

The real fix™ is to make TrueNAS export its metrics in a way that preserves the type information. Under the hood, it [appears to use collectd](https://www.truenas.com/docs/core/system/reporting/), which does support [Prometheus export](https://collectd.org/wiki/index.php/Plugin:Write_Prometheus), so this may be relatively straightforward to do upstream. While [this thread](https://www.truenas.com/community/threads/prometheus-on-scale.92134/) is about TrueNAS SCALE, I take it as evidence that the appetite for Prometheus support is there.
