### ISSUE TITLE
Metrics server dead after pushing metrics on GKE

### ISSUE THREAD

**Issue by yfried** [prometheus/graphite_exporter#168]
Hi,
I deployed the graphite exporter to k8s (basically copied from the statsd-exporter helm chart) and tried to push metrics using the prometheus python client.

This works fine locally, but on k8s, whenever I push, log shows the incoming metrics (parsed with labels) but the metrics server starts returning 500 errors until the liveness probe kills it.

I'm using this script:
```python
import logging
import random
import time

from prometheus_client import Counter
from prometheus_client.bridge.graphite import GraphiteBridge

_metric_sent_messages = Counter('test_metric', 'test sent messages',)

logging.getLogger().setLevel(logging.DEBUG)


def process_request(t):
    """A dummy function that takes some time."""
    _metric_sent_messages.inc()
    print(f"sleep({t})")
    time.sleep(t)


if __name__ == '__main__':
    # Start up the server to expose the Prometheus metrics.
    gb = GraphiteBridge(('prometheus-graphite-exporter.monitoring', 8090), tags=True)

    # Generate some requests.
    for i in range(10):
        process_request(random.random())
    print("push metrics")
    gb.push(prefix="demo.test")
```
my graphite config
```yaml
    mappings:
    - match: "*.*.*"
      name: "$3"
```

And my input arguments:

```
    - --web.listen-address=:8080
    - --web.telemetry-path=/metrics
    - --graphite.listen-address=:8090
    - --graphite.mapping-config=/etc/prometheus-graphite-exporter/graphite-mapping.yaml
    - --log.level=debug
```

I'll just add that when the metrics don't match the mapping (`*.*.*`) they show up fine at the metrics server with no issue

**Comment by matthiasr** [comment]
I'm going to close this issue, as changing the default metrics would be a breaking change for existing users, and I don't want to do that for a use-case that has better alternatives.
