### ISSUE TITLE
allow reloading config with kill -HUP (as with prometheus)

### ISSUE THREAD

**Issue by ibotty** [prometheus/graphite_exporter#17]
That would be nice for containers (where it's running as PID 1).

**Comment by matthiasr** [comment]
I'm going to have to say no to this, at least for the foreseeable future. Changing mappings on the fly is difficult to pull off correctly, and prone to introducing inconsistencies and bugs. What should we do if the new configuration is inconsistent? what if it is consistent but not what you wanted?

Especially with containers, I would strongly encourage you to consider the mappings as part of the code – don't rewrite them on the fly but treat changes to them with the same care as you would treat any code change
