### ISSUE TITLE
allow setting the metrics type

### ISSUE THREAD

**Issue by ibotty** [prometheus/graphite_exporter#18]
What about e.g. `__type__=counter` or similar?

It would also be nice to allow histograms, etc, but that might take more thought.

**Comment by brian-brazil** [comment]
I'm not sure the additional config complexity would be worth it for a tool that's meant to be only transitional, and data that's currently going to be thrown away.

**Comment by ibotty** [comment]
I tend to disagree. There are many projects out there (grafana is the one I am looking at right now) that send metrics to graphite. As an ops-person it would be nice to get good metrics out of software you don't actively develop.

**Comment by brian-brazil** [comment]
What has that to do with setting the type?

**Comment by ibotty** [comment]
Maybe we are miscommunicating. I'd like to get good (prometheus) metrics out of a graphite producing app. That means, I want them to be the right type. If I have counter, I'd like it to be a counter, because it's not a gauge.

**Comment by brian-brazil** [comment]
Are you aware that Prometheus currently does nothing with this information, and providing it may require substantially more complex graphite exporter configs?

This is likely one of those cases where trying to get perfect metrics out of a non-Prometheus monitoring system isn't worth the ongoing effort.
