### ISSUE TITLE
Build and push docker image to a different repository

### ISSUE THREAD

**Issue by colearendt** [prometheus/graphite_exporter#190]
DockerHub has instituted a number of per-day rate limits that cause issues for infrastructure maintenance (even on paid plans). As a result, it would be ideal to build and push docker images into another repository besides DockerHub.

Is current CI for docker image builds set up inside Docker Hub? I would be happy to contribute a GitHub Action workflow that can publish docker images to GHCR (GitHub Container Registry). Maintenance in my experience has been simple with GitHub Actions, because you can set up trust between the repository and the package repo. This would enable the image to be accessible without rate limits at: ghcr.io/prometheus/graphite_exporter

(There are a number of mirrors out there that mirror images from docker hub onto ghcr or another repo, but it is ideal if the builds come from the source)

**Comment by matthiasr** [comment]
The images are [available on quay.io](https://quay.io/repository/prometheus/graphite-exporter?tab=tags&tag=latest). The build and CI infrastructure is shared across github.com/prometheus – the GHCR support would have to be added there. Also FYI-tagging @roidelapluie who will work on GitHub actions and may have opinions on whether this is something we want.
