### ISSUE TITLE
Latest(version=0.12.2) Docker Image run fails

### ISSUE THREAD

**Issue by manju369** [prometheus/graphite_exporter#197]
Container created from latest image run fails  with an error message  `panic: runtime error: invalid memory address or nil pointer dereference`

>  /bin/graphite_exporter --graphite.mapping-config=/tmp/graphite_mapping.conf
ts=2022-07-09T13:11:34.432Z caller=main.go:83 level=info msg="Starting graphite_exporter" version_info="(version=0.12.2, branch=HEAD, revision=f08af21d9172537e6edae4ba0f4c9a3b1f039edf)"
ts=2022-07-09T13:11:34.432Z caller=main.go:84 level=info build_context="(go=go1.18.3, user=root@bf6b6725a07f, date=20220708-14:04:05)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x702cc4]
goroutine 1 [running]:
github.com/go-kit/log.(*context).Log(0xc00006ba40, {0xc000308000?, 0x4, 0xc0003041c0?})
	/go/pkg/mod/github.com/go-kit/log@v0.2.1/log.go:168 +0x384
github.com/prometheus/statsd_exporter/pkg/mapper/fsm.TestIfNeedBacktracking({0xc000152d00, 0x6, 0x4?}, 0x0, {0x0, 0x0})
	/go/pkg/mod/github.com/prometheus/statsd_exporter@v0.22.6/pkg/mapper/fsm/fsm.go:314 +0x410
github.com/prometheus/statsd_exporter/pkg/mapper.(*MetricMapper).InitFromYAMLString(0xc0001b03c0, {0xc0001a4a80, 0x31f})
	/go/pkg/mod/github.com/prometheus/statsd_exporter@v0.22.6/pkg/mapper/mapper.go:251 +0xfd3
github.com/prometheus/statsd_exporter/pkg/mapper.(*MetricMapper).InitFromFile(0xa67fe0?, {0x7ffc7365a82b?, 0x1?})
	/go/pkg/mod/github.com/prometheus/statsd_exporter@v0.22.6/pkg/mapper/mapper.go:275 +0x5e
main.main()
	/app/cmd/graphite_exporter/main.go:92 +0x55e

However docker image `prom/graphite-exporter:v0.12.0` (version=0.12.0) works fine without any issue 

>  /bin/graphite_exporter --graphite.mapping-config=/tmp/graphite_mapping.conf
level=info ts=2022-07-09T13:14:16.774Z caller=main.go:81 msg="Starting graphite_exporter" version_info="(version=0.12.0, branch=HEAD, revision=fd93180b8849202b81c6c821956dd9c52b11e1de)"
level=info ts=2022-07-09T13:14:16.775Z caller=main.go:82 build_context="(go=go1.17.3, user=root@cb107647cffb, date=20211201-08:29:28)"
WARN[0000] backtracking required because of match "*.*.executor.threadpool.*", matching performance may be degraded  source="fsm.go:313"
WARN[0000] backtracking required because of match "*.*.jvm.*.*", matching performance may be degraded  source="fsm.go:313"

So, I suspect some issue is with the latest version(v0.12.2)
PS: I do not know Golang :(

**Comment by Scrin** [comment]
I ran into this same issue after updating from 0.12.1 to 0.12.2. The issue seems to be related to custom mappings, if I omit the use of `--graphite.mapping-config=/my/custom/mapping.yml` the exporter starts up just fine.

**Comment by lucasmaurice** [comment]
Same issue for me, as soon as I add more than one match in my mapping I have the issue.
I use the compiled binary from this archive: `graphite_exporter-0.12.2.linux-amd64.tar.gz` (https://github.com/prometheus/graphite_exporter/releases/download/v0.12.2/graphite_exporter-0.12.2.linux-amd64.tar.gz)

**Comment by lucasmaurice** [comment]
The mapping work fine for me when I use `match_type: regex`.

**Comment by matthiasr** [comment]
It looks like I missed passing in a logger correctly to the refactored mapper. I'll try to fix it as soon as possible, or would gladly accept a PR
