### ISSUE TITLE
Dash and underscore character escaping

### ISSUE THREAD

**Issue by spynode** [prometheus/graphite_exporter#22]
Documentation mentions that `-`,`_` in metric names are escaped into `__`, but I do not see this happening. All symbols in metric names are replaced with single `_`. I skimmed through the code but could not locate where this is implemented. Should this documented functionality be in place for 0.1.0 release?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/graphite_exporter/blob/master/mapper.go#L132

**Comment by spynode** [comment]
Thanks for quick response. According to documentation, metric name `ab.ab-c.12_3.d` should be transformed into `ab_ab__c_12__3_d`, but instead gets transformed to `ab_ab_c_12_3_d`.

**Comment by brian-brazil** [comment]
Hmm, I can't remember the code ever doing that. Would you mind sending a PR to fix the docs?

**Comment by spynode** [comment]
Would you consider taking a look at PR where this functionality is implemented?

**Comment by brian-brazil** [comment]
We don't implement anything like that anywhere else we sanitize metric names, so I don't think it'd make sense to start doing it here.

**Comment by spynode** [comment]
This functionality has use case when one needs a metric tree as in Graphite, and still have some special chars in metric names, which do not act as level delimiters.

**Comment by brian-brazil** [comment]
Prometheus has no notion of levels, we use single underscores for that by convention.
