### ISSUE TITLE
"Too many files" - TCP connection exhaustion

### ISSUE THREAD

**Issue by threemachines** [prometheus/graphite_exporter#25]
Hi - 

Our graphite-exporter is throwing:
`ERRO[669315] Error accepting TCP connection: accept tcp [::]:9109: accept4: too many open files  source=main.go:219`

lsof shows that the exporter has more than 1000 open TCP connections - from 20 servers.

This seems like it's probably the same issue seen in https://github.com/prometheus/prometheus/issues/2238. I'm looking into updating our grafana version, but would it be practical to port the limiter from that issue to the graphite exporter?

Thanks!

**Comment by brian-brazil** [comment]
Considering the entire purpose of the graphite exporter is to accept connections from other servers, a limit here would be solving the wrong problem. I'd suggest bumping the ulimit, and fixing those servers.

**Comment by threemachines** [comment]
Actually it's starting to look like this might be on the exporter end - we're sending our graphite metrics via Diamond, which has its own implementation of the protocol, and it sure looks like the graphite exporter is holding open connections which don't even have a process on the other end anymore.

I'll do some more digging and try to really isolate the issue.

**Comment by brian-brazil** [comment]
Hmm, can you share a goroutine dump?

**Comment by threemachines** [comment]
Well, this is the strangest thing. We put a carbon relay in between our Diamond collectors and the graphite_exporter, and as an apparent side effect of that, the number of sockets on the graphite_exporter has been totally stable. (But we also haven't seen a leak on the relay, so it may not be as simple as an issue with the Diamond side of the connections, either.)

In any case, we aren't affected by this issue any longer... if anybody else has the same issue, throwing a relay in front is a pretty easy workaround. (I used https://github.com/graphite-ng/carbon-relay-ng)
