### ISSUE TITLE
Mapping configuration check

### ISSUE THREAD

**Issue by deejay1** [prometheus/graphite_exporter#31]
Hi, it would be nice if graphite_exporter would allow for checking the correctness of the mapping file as a runtime switch, so it could be used like promtool in a CI/CD flow.

**Comment by l15k4** [comment]
Yeah, that would be handy.  The parsing is a mystery to me anyway, if I take the README configuration : 
```
mappings:
- match: test.dispatcher.*.*.*
  name: dispatcher_events_total
  labels:
    action: $2
    job: test_dispatcher
    outcome: $3
    processor: $1
```

I get : 
```
INFO[0000] Starting graphite_exporter (version=0.2.0, branch=master, revision=e76b500729ba944f7370d58c43f431632da339e5)  source=main.go:196
INFO[0000] Build context (go=go1.7.5, user=root@afcddccec7e5, date=20170301-17:28:10)  source=main.go:197
FATA[0000] Error loading metric mapping config: Line 1: expected label mapping line, got: - match: test.dispatcher.*.*.*  source=main.go:207
```

Indentation doesn't seem to be an issue here. What is going on ???

**Comment by matthiasr** [comment]
You are using version 0.2.0, the YAML format came in in version 0.3.0.

**Comment by l15k4** [comment]
A see, it was not pushed, I'm using the : 
```
docker pull prom/graphite-exporter

docker run -d -p 9108:9108 -p 9109:9109 -p 9109/udp:9109/udp
        -v $PWD/graphite_mapping.conf:/tmp/graphite_mapping.conf \
        prom/graphite-exporter --graphite.mapping-config=/tmp/graphite_mapping.conf
```

**Comment by matthiasr** [comment]
Can you please run `docker pull prom/graphite-exporter && docker run prom/graphite-exporter --version` and paste the full output?

**Comment by l15k4** [comment]
Sorry @matthiasr, my bad. Thank you

**Comment by matthiasr** [comment]
Related: https://github.com/prometheus/statsd_exporter/issues/263

since we are using the statsd mapping package here, the mechanics would be _almost_ the same.
