### ISSUE TITLE
Allow substring wildcards

### ISSUE THREAD

**Issue by isavcic** [prometheus/graphite_exporter#32]
This is, for some reason, an invalid mapping config:
```
sensu.Foo-*.*.*
name="sensu"
foo="$1"
bar="$2"
baz="$3"
```
If I remove `Foo-` it passes the mapping check. Why is the mapping check so "strict" that it doesn't allow the wildcard anywhere but on its own, ie. between dots?

Thanks.

**Comment by brian-brazil** [comment]
That's probably something to handle via relabelling, as such usage indicates incorrect label usage on the part of the client so I'm not sure we should support that.

**Comment by isavcic** [comment]
I agree that relabeling would "adjust" the metrics once Prometheus picks them up, but by allowing substring wildcards you can also cherry-pick the metrics that get passed on to Prometheus in the first place. I'm not seeing the downside to this, TBH.

**Comment by brian-brazil** [comment]
The downside is that this is going against both the Graphite and Prometheus data models.

> by allowing substring wildcards you can also cherry-pick the metrics that get passed on to Prometheus in the first place

This exporter does not support that, and what you propose doesn't change that.

**Comment by isavcic** [comment]
If the substring wildcards are allowed and `--graphite.mapping-strict-match` is enabled, this configuration for example exposes only the metrics starting with `sensu` and having the word `Surfer-` in the third part of the metric:
```
sensu.*.Surfer-*.*
name="surfer"
host="$1"
check="$2"
url="$3"
```
I don't see how the "exporter doesn't support that", but I do feel that there is a strong, albeit unwritten "this exporter does this and must not do that" set of rules, so I'm dropping this. I'll just fork it and change it. Closing this issue. Thanks.
