### ISSUE TITLE
Use YAML configuration format

### ISSUE THREAD

**Issue by matthiasr** [prometheus/graphite_exporter#38]
… to fit in with the rest of the Prometheus ecosystem. Probably also fits in better with #37.

**Comment by matthiasr** [comment]
Fixed by #52.

**Comment by l15k4** [comment]
Hey, is it possible that the example configuration in README is not valid ? https://github.com/prometheus/graphite_exporter/issues/31#issuecomment-419030347

**Comment by matthiasr** [comment]
As discussed there – the example is correct, the errors were caused by an old version of the Docker image.
