### ISSUE TITLE
graphite_exporter issue

### ISSUE THREAD

**Issue by ShruthiRamachandra** [prometheus/graphite_exporter#46]
Hi Team,

I am trying to use graphite_exporter on RHEL (6/7). i am configuring this to monitor spark metrics.
When i start graphite service, i am getting below error message. 
Please let me know the fix.

graphite_exporter[3551]: time="2018-04-26T11:30:43+08:00" level=info msg="Invalid part count of 2 in line: Accept-Encoding: gzip" source="main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:43+08:00" level=info msg="Invalid part count of 2 in line: X-Prometheus-Scrape-Timeout-Seconds: ...main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:43+08:00" level=info msg="Invalid part count of 1 in line: " source="main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid value in line: GET /metrics HTTP/1.1" source="main.go:112"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid part count of 2 in line: Host: localhost:9109" source="main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid part count of 2 in line: User-Agent: Prometheus/2.2.1" source="main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid part count of 2 in line: Accept: text/plain;version=0.0.4;q=1,...main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid part count of 2 in line: Accept-Encoding: gzip" source="main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid part count of 2 in line: X-Prometheus-Scrape-Timeout-Seconds: ...main.go:94"
graphite_exporter[3551]: time="2018-04-26T11:30:48+08:00" level=info msg="Invalid part count of 1 in line: " source="main.go:94"

**Comment by kfkonrad** [comment]
Take a look at `main.go`. Seriously, the source code explains it quite well. It's a fairly simple error even though I don't find it very descriptive. Your graphite plaintext input is malformatted. A missing timestamp or extraneous whitespace is likely the underlying error.
