### ISSUE TITLE
Unexpected mappings behavior

### ISSUE THREAD

**Issue by l15k4** [prometheus/graphite_exporter#57]
Hey, I'm using graphite_exporter to convert druid metrics to prometheus format. I get a metric like this : 
```
echo "druid_druid_coordinator_musty_bear_druid_coordinator_0_musty_bear_druid_coordinator_default_svc_cluster_local:8081_jvm_gc_mem_capacity 1.79306496e+08" | nc localhost 9109
```

Applying this mapping : 
```
mappings:
  - match: druid_druid_(.*?)_(.*)_:\d{4}_(.*) (.*)$
    match_type: regex
    name: druid_component_metrics
    labels:
      component: "$1"
      metric: "$3"
      value: "$4"
```

Probably doesn't match so one would expect the metric to be present in the original form, but it is not present in metrics at all. Not even in the original form.

And there is an error in logs : 
```
time="2018-09-06T15:34:52Z" level=info msg="Invalid part count of 2 in line: druid_druid_coordinator_musty_bear_druid_coordinator_0_musty_bear_druid_coordinator_default_svc_cluster_local:8081_jvm_gc_mem_capacity 1.79306496e+08" source="main.go:108" 
```

If I understand it correctly, mapping cannot have more regex groups than it is actually used in labels, is that correct ?

**Comment by l15k4** [comment]
I see : 
https://github.com/prometheus/graphite_exporter/blob/19f9a6f7de0b8ea55b795b4bdf6720a65e236d4e/main.go#L105-L110

Druid is producing metric lines with 2 parts instead of 3 ... so this is basically incompatible with Druid

**Comment by l15k4** [comment]
Ok, this is weird : 
```
/ # echo "test_tcp 1234 $(date +%s)" | nc localhost 9109
/ # wget http://localhost:9108/metrics
/ # cat metrics | grep test
test_tcp 1234
```

^^^ the timestamp is not present in the metrics endpoint ... and it leads to an pattern matching error : 
```
time="2018-09-06T20:52:50Z" level=info msg="Invalid part count of 2 in line: test_tcp 1234" source="main.go:108" 
```

**Comment by matthiasr** [comment]
I'm not familiar with druid, can you link to some information about it? Does Graphite accept the 2-part metrics?

**Comment by matthiasr** [comment]
Do not get confused by the /metrics endpoint. The Prometheus format has nothing to do with the Graphite line protocol and is not fed back into that.

**Comment by l15k4** [comment]
Yeah well, I think that it would be really helpful if the debug log level was showing incoming metrics and the resulting prometheus metrics, so that one could set it up easily. Otherwise folks use tcpdump to figure out what's wrong in case of unexpected behavior ...

**Comment by l15k4** [comment]
I'm still digging into this and this is unexpected : 
```
time="2018-09-18T15:46:30Z" level=debug msg="Incoming line : druid.druid/historical.jvm/mem/used 51945456 1537285231" source="main.go:106" 
time="2018-09-18T15:46:30Z" level=debug msg="Sample: {OriginalName:druid.druid/historical.jvm/mem/used Name:druid_metrics Labels:map[component:historical.jvm metric:] Help:Graphite metric druid.druid/historical.jvm/mem/used Value:5.1945456e+07 Type:2 Timestamp:2018-09-18 
```
This is the raw line : 
```
druid.druid/historical.jvm/mem/used 51945456 1537285231
```
This is my mapping : 
```
mappings:
- match: druid\.druid/(.*?)/(.*?)
  match_type: regex
  name: druid_metrics
  labels:
    component: $1
    metric: $2
```
And the result has empty `metric` : 
```
Labels:map[component:historical.jvm metric:]
```

**Comment by matthiasr** [comment]
Side note, not actually the problem here:

[Graphite docs](https://graphite.readthedocs.io/en/latest/terminology.html#term-series) are vague about it, but looking at [this question](https://graphite.readthedocs.io/en/latest/terminology.html#term-series) it's pretty clear that slashes are not a valid as part of the metric name. It's accidental that this exporter actually lets you do that.

**Comment by matthiasr** [comment]
I experimented around a bit and it seems the problem is the `(.*?)` construction – I don't think that's a valid regular expression. What are you trying to express there? I tried with `(.+)` and that works correctly.

**Comment by l15k4** [comment]
I'm from the JVM land :-) Greedy/Reluctant/Possesive quantifiers https://docs.oracle.com/javase/tutorial/essential/regex/quant.html

Thanks, I will try that out !

**Comment by matthiasr** [comment]
Go uses [RE2 syntax](https://github.com/google/re2/wiki/Syntax)
