### ISSUE TITLE
Improve scrape performance with a lot of metrics

### ISSUE THREAD

**Issue by GiedriusS** [prometheus/graphite_exporter#66]
I am performing some load tests with the Graphite exporter and once the metrics count passes a certain threshold, the performance becomes really bad. For example, while pushing metrics with `banno/graphite-tester` with this command: `docker run -it banno/graphite-stresser:0.1 my.graphite.exporter.com 9109 50 650 10 false` (650 timers from 50 hosts which means 487500 metrics), the downloading of all metrics from `/metrics` sometimes takes around 30 seconds with `curl`. As I can see from `curl`, it takes a very long time until the download starts at all but when it starts it finishes immediately. The node metrics from that machine show that load isn't so high and there is plenty of RAM - it is a 64GB and 16 vCPUs Openstack machine on KVM. Thus, it seems that something is wrong with the code.

Afterward, looking at the code it seems that for each small sample that comes in or for any access whatsoever, the whole map which holds the samples gets locked by using a `sync.Mutex`. My theory is that there a lot of different writers because of the huge number of metrics and the one sole reader gets starved.

My small suggestion would be to switch to a https://golang.org/pkg/sync/#Map and not lock the whole map on any single access. *Or* please let me know how I could debug this problem further :)

**Comment by matthiasr** [comment]
> 650 timers from 50 hosts which means 487500 metrics 

it's possible to scrape this many metrics in one go, but it's not particularly common in Prometheus. This can also cause issues on the server ingestion side so I'd recommend running one exporter per host and scraping them separately in this scenario.

That being said, there is certainly potential to optimize this. You're _probably_ on the right track for one cause, but I'm curious what else there is. Would you mind producing some CPU profiles while this is happening? I imagine they will be informative.

**Comment by GiedriusS** [comment]
Ok, I can do that but as a off-topic please fix the pprof end-points then because https://github.com/prometheus/graphite_exporter/blob/master/main.go#L297 matches everything and it doesn't matter if you go to `/debug/pprof/heap` or any other `/debug/*` end-point because that handler matches everything. You could add a check like that inside:
```
		if r.URL.Path != "/" {
			http.NotFound(w, req)
			return
		}
```

**Comment by matthiasr** [comment]
Can you send a PR for this please?

**Comment by GiedriusS** [comment]
Submitted https://github.com/prometheus/graphite_exporter/pull/67 to unblock the pprof end-points.

**Comment by matthiasr** [comment]
I'll test and merge that as soon as I can, for now you can run your tests
with a locally built version (`make build`).

**Comment by GiedriusS** [comment]
[profiling_output.pdf](https://github.com/prometheus/graphite_exporter/files/2652834/profiling_output.pdf)
Here is the CPU profiler result over 30s. with the current version. So it seems like it spends 33.03% on the lock, and the other major part is coming from client_golang.
Would you be willing to accept changes to use sync.Map if it helps with that part of CPU usage? I will prepare a patch locally and check if it helps by running the profiler again.

**Comment by matthiasr** [comment]
Is this still an issue? We have updated the Prometheus client significantly since 2018.

**Comment by GiedriusS** [comment]
I guess not. Plus unfortunately but at $WORK we don't use `graphite-exporter` much so there's not that much interest from me anymore :/ Let's close this and then re-open if someone wants to do this.
