### ISSUE TITLE
Upgrade client_golang to v0.8.0 or newer

### ISSUE THREAD

**Issue by matthiasr** [prometheus/graphite_exporter#69]
statsd_exporter is already using it, and with Go modules this prevents us from bringing in a newer version of the mapper.

There are also performance improvements in client_golang, so this will probably help with #66 as well.

**Comment by beorn7** [comment]
Note that some of the performance improvements are in prometheus/common, which is un-versioned so far and needs to be updated separately from client_golang.

**Comment by matthiasr** [comment]
fixed by #77
